apiVersion: v1
kind: Pod
metadata:
   name: ubuntu-pod
spec:
   containers:
   - name: ubuntu-container01
     image: amrishjaindev/amrish-devops-poc:v_1
     ports:
     - containerPort: 80
       hostPort: 85
     command:
      - "sleep"
      - "604800"
     imagePullPolicy: IfNotPresent
     name: ubuntu
   restartPolicy: Always  
